name: Stress builds

on:
  workflow_dispatch:

jobs:
  stress_ub:
    runs-on: ${{ matrix.os }}
    strategy:
            fail-fast: false
            matrix:
                    os: [ubuntu-18.04]
                    build_type: [release, debugoptimized]

    steps:
   
    - name: Dump info
      run: |
              lsblk -o NAME,MODEL
              cat /proc/swaps

    - name: Install dependencies
      run: |
              sudo apt-get update
              sudo apt-get install build-essential libbsd-dev pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-dev libcurl4-openssl-dev
              sudo apt-get install libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev
              python3 -m pip install --user setuptools_rust wheel
              python3 -m pip install --user poetry
    - uses: actions/checkout@v2

    - name: Setup python environment to run branch
      run: |
              poetry install

    - name: Build setup with YCSB, tools and configs
      run: |
              sed -i.bak "s,ssh://git@bitbucket.micron.com/hse/hse-python.git,https://${{ secrets.GH_TOKEN }}@github.com/bhaveshvasandani/hse-python.git,g" subprojects/hse-python.wrap
              poetry run meson builddir -Dbuildtype=${{ matrix.build_type }} -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true -Dwrap_mode=forcefallback

    - name: Run tests
      continue-on-error: true
      run: |
              poetry run meson test -C builddir --suite=stress --print-errorlogs --no-stdsplit

    - name: list var-log
      run: |
              ls -al /var/log/

    - name: list var-log-journal
      run: |
              sudo ls -al /var/log/journal
            
    - name: list tmp
      run: |
              ls -al /tmp

    - name: cat syslog
      run: |
              sudo cat /var/log/syslog

    - uses: actions/upload-artifact@v2
      # if: failure()
      with:
        name: build-artifact-ubuntu-${{ matrix.build_type }}
        path: |
                builddir/meson-logs/
                /var/log/syslog
